.github/workflows/release.yml

feature: automatic release creation

---

emojiProcessor.go

fix: #6 
change  Regex pattern

fix: change  Regex pattern

---

emoji.go
emojiProcessor.go

申請後にチャンネルを削除＋スレッドをロック及びアーカイブ化するように
resolve #4

impl: add channel close functions

---

emojiProcessor.go
main.go

fix: change return message

---

emoji.go
main.go

impl: User feedback implementation.

---

main.go

fix: Fixed not being able to press a button after making a request

---

emoji.go
main.go
misskey.go

impl: added emoji note function

---

main.go

fix: add interaction message

---

emoji.go
main.go

fix: add emoji length check

---

emoji.go

add abort function

---

main.go

fix: add channel name check

---

.github/workflows/release.yml

fix: release message

---

main.go
user.go

add: check permission func

---

command.go
component.go
emoji.go
emojiProcessor.go
main.go
misskey.go

change: use logrus

---

component.go
emoji.go
request-handler.go

change: separation of licenses and remarks

---

main.go

fix: change logger level timing

---

main.go
request-handler.go

fix: responce state

---

component.go
main.go

change: channel to threads

---

emoji.go
main.go
misskey.go
request-handler.go

fix: properly reflect values

---

component.go
request-handler.go

fix: nsfw button

---

misskey.go

fix: license field

---

component.go

change: ratelimi

---

request-handler.go

#76 絵文字を指定しなければいけない部分が空欄だった問題を修正

fix request button

---

component.go

change thread auto archive duration time (24h)

---

component.go

add thread url

---

component.go
emoji.go
main.go
request-handler.go
utilities.go

add auto remove process

---

component.go
request-handler.go

change message

---

emoji.go

fix uuid version

---

emoji.go

承認/却下時のメッセージに絵文字名を追加
Closes #85

承認/却下時のメッセージに絵文字名を追加

---

request-handler.go

chore: refine request messages

---

cmd/main.go
pkg/command/nirila_command.go

add version command

---

Dockerfile

fix docker settings

---

pkg/component/emoji_request_component.go

add request user detail

---

pkg/config/config.go
pkg/handler/emoji/emoji_handler.go
pkg/handler/emoji/emoji_moderation_reaction_handler.go
pkg/repository/emoji_repository.go

add save system

---

pkg/command/emoji_list_command.go
pkg/container/container.go
pkg/repository/emoji_gorm_repository.go

絵文字申請一覧コマンドを追加

---

pkg/bot/bot.go
pkg/config/config.go
pkg/container/container.go
pkg/handler/processor/upload_handler.go
pkg/job/database_backup_job.go
pkg/repository/s3_repository.go
pkg/utility/utilities.go

closes #96
メッセージ送信時にモデレータにも反応してしまう。
そのため申請者以外に反応しないよう修正
スコープ
- メッセージのみ
ボタンなどは別途PRやissueに記述する

#96 申請者のみに応答するよう変更

---

pkg/component/emoji_overwrite_confirm_component.go
pkg/config/config.go
pkg/container/container.go
pkg/entity/emoji.go
pkg/entity/legacy_emoji.go
pkg/handler/processor/name_setting_handler.go
pkg/migration/json_migration.go
pkg/repository/misskey_repository.go
settings.env

add: jsonデータをimportできるように

---

pkg/entity/emoji.go

related: #136 
IsNotifiedカラムを追加

add: 通知されたかどうかを確認するカラムを追加
